### ISSUE TITLE
How publishing works on front page

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#103]
When visiting the site I want an overview of how I use Flowershow to publish my stuff so that I have a better idea how to use it and if i want to use it

* Have your content on disk
* Download `flowershow` app/cli (`npm install flowershow` or even `npx flowershow publish` or download it)
* In your directory run `flowershow publish [filename]`
* Get a response like: live at https://xyz.flowershow.sites/

Inspiration from https://www.contentlayer.dev

![image](https://user-images.githubusercontent.com/180658/185150359-dacbf187-5bd1-4393-8bac-0c1198ec78e7.png)

## Acceptance

* [X] Front page has a step by step guide even with bullet points and headings **✅ 2022-08-17 basic version - How it works section with 3 steps **
* [x] Nicely illustrated like contentlayer (Bonus)

**Comment by olayway** [comment]
@rufuspollock I've created a very simple version of it with 3 steps, you can see it live

**Comment by rufuspollock** [comment]
@olayway looks good - now we can make it fancy 😄

**Comment by rufuspollock** [comment]
@olayway this was what we could term "cloud" publishing. I think we could do the same for self-publishing given feedback in e.g. #119. Opened new issue for that in #125 and clarified title of this issue.
