### ISSUE TITLE
Make algolia search optional

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#108]
Not everyone needs Algolia search on their website I think. Let's maybe hide it by default and add an option to enable it in the config file so that people who don't have Algolia set up don't have a nonworking search field in their navbars.

**Comment by olayway** [comment]
@rufuspollock, @khalilcodes what do you think?

**Comment by rufuspollock** [comment]
@olayway big +1. I think probably pliny has done this well https://github.com/timlrx/pliny - https://github.com/timlrx/pliny/pull/35

**Comment by rufuspollock** [comment]
@khalilcodes is this now done as part #161 ?

**Comment by khalilcodes** [comment]
This was resolved in PR #161 
 * commit [d5a607e](https://github.com/flowershow/flowershow/commit/d5a607e778fd4011438fe19ad7b9898cdccba02f)
