### ISSUE TITLE
allow publishing to own infrastructure

### ISSUE THREAD

**Issue by airtonix** [flowershow/flowershow#119]
- I don't want to use your `https://*.flowerapp.sites`
- I want to push it to my own s3/vercel/githubpages/ssh/whateverhostingbbqomg

**Comment by rufuspollock** [comment]
@airtonix thanks for the feedback and that's already possible and we can make that clearer on the front page that "self-publishing" is possible as well.

**Comment by rufuspollock** [comment]
FIXED. @airtonix this is resolved with the release of self publishing tutorial and functionality https://flowershow.app/docs/publish-tutorial
