### ISSUE TITLE
Blog feature design

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#150]
Design the blog feature both in UX and implementation.

## Acceptance

  **🚧 2022-11-17 https://hackmd.io/kXy3EyzjROeZuBASmT4E7Q**

- [x] job stories written **✅2022-11-18  see https://flowershow.app/meta/blog-design**
- [x] ideas for implementation **✅2022-11-18 see https://flowershow.app/meta/blog-design**

**Comment by rufuspollock** [comment]
Work in progress in https://flowershow.app/meta/blog-design

**Comment by olayway** [comment]
Analysis still to be written down - https://hackmd.io/kXy3EyzjROeZuBASmT4E7Q

**Comment by rufuspollock** [comment]
@olayway your additional comments have been great and really changed the design - i think the component approach is way to go and we can get rid of pagination! I've just refactored design taking these into account and moved to: https://flowershow.app/meta/blog-design. I've integrated this material into #35

**Comment by rufuspollock** [comment]
FIXED - see https://flowershow.app/meta/blog-design and updates in #35 and #296
