### ISSUE TITLE
Importing components (in MDX) that use external packages doesn't work

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#157]
@khalilcodes, @rufuspollock it seems importing components that depend on external packages doesn't work indeed 😞 I believe it has to do with Contentlayer's configuration/usage of `mdx-bundler`. When you actually define the component and import it's dependencies directly in MDX file (not import them from a file) everything works. So it has sth to do with imports resolution I guess. Anyways, I've created an issue in Contentlayer's repo for that: https://github.com/contentlayerdev/contentlayer/issues/302

You can also test it yourself. I've added relevant tests  to `/content/test/components-import.md` so that Contentlayer's team can reproduce the issue.

I think we should also get acquainted with Contentlayer's source code sometime, and also with the docs of `mdx-bundler`', which they are using under the hood, so that it's not a complete black box for us.

_Originally posted by @olayway in https://github.com/flowershow/flowershow/issues/111#issuecomment-1241198848_

**Comment by rufuspollock** [comment]
We have a resolution thanks to [a comment](https://github.com/contentlayerdev/contentlayer/issues/302#issuecomment-1253765070) from @timlrx 

> Hi Ola,
> 
> That's because the import is not being resolved properly. `contentlayer` uses the [content file directory as the cwd](https://github.com/contentlayerdev/contentlayer/blob/503e1fe17565e784dca76946a4e3365fd6838eb6/packages/%40contentlayer/core/src/markdown/mdx.ts#L31-L33) but `node_modules` is not present in the folder and thus the import node resolution fails. One workaround is to define `cwd` to the current directory:
> 
> ```js
> export default makeSource({
>     mdx: {
>       cwd: process.cwd(),
>   }
> })
> ```
> 
> and modify the imports relative to the root folder:
> 
> ```js
> import LibTest from "./components/custom/LibTest.jsx"
> ```
> 
> Hope that helps!
