### ISSUE TITLE
Feature Testing using playwright round 2 part II: more tests with new fixtures

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#178]
We want to test more features of the template app so that as we add things we know we aren't breaking anything

## Acceptance

* [x] Key features of template are under test

## Tasks

Select more stuff to test (and e.g. philippe can have a go)

* [x] Review main features and pick a few key things we want to test
* [x] Syntax
  * [x] #118 
  * [x] wikilinks
  * [x] CommonMark
  * [x] GFM

**Comment by PhilippeduPreez** [comment]
FIXED [here](https://github.com/flowershow/flowershow/pull/180/commits/77a4a6f4630f8d5d4623051455733a3eb4c933e0)
Tests work locally, but there is still an error with current playwright setup to be fixed in next PR
