### ISSUE TITLE
Monorepo setup and scaffolding

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#18]
We will have various things in here probably so let's do the monorepo setup.

## Acceptance

* [x] Monorepo setup with `flowershow` package in it at `packages/flowershow` **🚧2022-10-25 ❓ think we could rename CLI to be named flowershow consistent with npm naming**  **✅ 2022-10-31 olayway: from what I see in how nx handles creating new packages/apps by their generators in monorepos, how they do this in their docs but also how community does it, it's best to have all our packages published under flowershow organization, and publish them as scoped packages, i.e. they will be available under prefix `@flowershow`. Cool thing about it is that we can name our packages whatever we want and we don't have to worry about name clashes with some other public packages, so we can have our CLI package named just `cli`, and it will be published under `@flowershow/cli`**
* [x] Moved `templates/default` into `packages` e.g. at `packages/template` (we can drop default for now!)
* [x] Linting and prettier in right place
* [x] tests in right place
* [x] changeset setup documented for monorepos (in e.g. flowershow.app/docs/developers

### Preliminaries

* [x] Compare briefly monorepo tools e.g. nx, lerna, turborepo and make a choice
  * [ ] Brief summary of each
  * [x] Choice **✅2022-07-01 Let's go with nx**
* [x] Create `packages/` directory **✅2022-08-?? done**
* [x] Setup nx **🚧2022-10-25 ❓ is this relevant anymore?**
* [x] Briefly document for other devs about anything they need to do in e.g. base README.md 

### Doing the work

* [x] Monorepo setup with `flowershow` package in it at `packages/flowershow` **🚧2022-10-25 ❓ think we could rename CLI to be named flowershow consistent with npm naming**
* [x] Moved `templates/default` into `packages` e.g. at `packages/template` (we can drop default for now!)
* [x] Linting and prettier in right place
* [x] changeset setup documented for monorepos (in e.g. flowershow.app/docs/developers

**Comment by olayway** [comment]
https://github.com/flowershow/flowershow/issues/187#issuecomment-1262358821
>@olayway i think we want to move templates default into packages with a name like template-default or even app-default (though app is overused), or even, app-template-default

**Comment by olayway** [comment]
@rufuspollock I'd recommend we also include all our remark plugins in our monorepo (maybe next sprint)
