### ISSUE TITLE
Investigate high severity vulnerabilities

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#200]
Investigate and fix 11 high severity vulnerabilities reported by npm.

**Comment by PhilippeduPreez** [comment]
npm audit fix:

![image](https://user-images.githubusercontent.com/44789132/200544379-737bc1f9-2c86-473f-9679-ac19c88fd8aa.png)

**Comment by PhilippeduPreez** [comment]
![image](https://user-images.githubusercontent.com/44789132/200545730-5b4bd5eb-560a-47ec-bc3c-482223bc7181.png)

**Comment by PhilippeduPreez** [comment]
Also tried removing package.json.lock and node modules and run npm i --legacy-peer-deps.

**Comment by PhilippeduPreez** [comment]
It seems like d3-color not being 1.3.0 was causing the most problems, I tried following https://itnext.io/fixing-security-vulnerabilities-in-npm-dependencies-in-less-than-3-mins-a53af735261d to see whether it worked. It seemed like it worked with the project having 0 vulnerabilities. We will just have to check if forcing the update does not cause any problems as it is used in a couple of other packages

**Comment by olayway** [comment]
@PhilippeduPreez it seems that mermaid developers have already been working on this issue. The package which was causing the issue was `dagre-d3`, which they have just replaced with `dagre-d3-es`. I've seen their merged the changes only yesterday and for now only to the development branch, so we may need to wait until the next release. I'm marking this issue as blocked for now.

For reference:
https://github.com/mermaid-js/mermaid/pull/3712
https://github.com/mermaid-js/mermaid/issues/3666
https://github.com/mermaid-js/mermaid/pull/3809

**Comment by sidharthv96** [comment]
@olayway I guess this should be fixed now?

**Comment by rufuspollock** [comment]
FIXED. We can close this as all resolved.

@sidharthv96 thanks for the prompt.
