### ISSUE TITLE
Wikilinks in callouts headings don't work

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#201]
One minor limitation is that wiki links do not parse in the callout's **header** section (works in body), although other markdown stuff does just as in Obsidian. For eg ..

```js
> [!tip] # custom title // this works (parses the title as h1)

> [!tip] [[wiki-link]] // this doesn't -->  shows Tip instead

> [!tip]
> [[wiki-link]] // this works
```

I will update the tasks shortly.

_Originally posted by @khalilcodes in https://github.com/flowershow/flowershow/issues/60#issuecomment-1263808308_

**Comment by rufuspollock** [comment]
As product owner i'd class this as very low priority as seems a pretty special case. @olayway have you run into this at all in our site yet?

**Comment by olayway** [comment]
No, I have created this issue, so that we don't forget about it:
> @khalilcodes imo headings in blockquotes being linked is not the end of the world (though imperfect - we can live for now and revisit - e.g. open an issue to remind ourselves of this and close this one).

**Comment by rufuspollock** [comment]
WONTFIX. very minor issue and something we won't support for now.
