### ISSUE TITLE
don't create .flowershow folder if the installation fails

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#212]
Atm flowershow template is copied to `.flowershow` right after running `npx flowershow install` (or `npx flowershow install path-to-some-target-dir`). But the installation can fail if e.g. the wrong path is passed to one of the prompts.

Solution: first do path checks, then degit the template to `.flowershow`.

**Comment by rufuspollock** [comment]
@olayway i would collect all these "bugfix" issues in one issue for now as probably some of them inter-relate. I also note you can achieve the result in a few different ways e.g. removing .flowershow in a `finally` statement on exception etc.

**Comment by olayway** [comment]
Actually, I have already solved it while working on the alpha release version. I forgot to close this issue.
Commit: 85776cc12d4fb8a680ed1135432d79ca5d0d058e
