### ISSUE TITLE
Error when trying to unlink Unix symlinks on Windows

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#218]
When running `npx flowershow install` on Windows:

![image](https://user-images.githubusercontent.com/52197250/197335753-4b63e292-74bb-425b-a94a-382ac38f45ac.png)

**Comment by rufuspollock** [comment]
@olayway for now, it could be simplest to say we don't support windows until we figure out a solution for these kind of issues.

**Comment by olayway** [comment]
I've gave it a try fixing it but I don't really have an option now to develop on windows so for now we'll be displaying a warning in the console if sb tries to run it on Windows.

https://github.com/flowershow/flowershow/commit/1da0a98cfeaba40ff8834ef7d621a3217a133d8d

I have also created a separate issue for working on support for Windows (#234), so I'm closing this one.
