### ISSUE TITLE
Add firstname field to email sign up

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#232]
We are currently not capturing names or surnames for our email list. Adding name introductions in our emails will help with not going to spam

# Tasks
- [x] Add name field to email signup **✅ 2022-10-28 done**
- [ ] Check options for forwarding signups to mailchimp **Not priority atm**

**Comment by olayway** [comment]
@PhilippeduPreez I've just added the name input next to the email input. But for some reason now after hitting "Notify me", the `subscribed` page is not displayed but rather 404. But I'm on it!

**Comment by olayway** [comment]
> @PhilippeduPreez I've just added the name input next to the email input. But for some reason now after hitting "Notify me", the subscribed page is not displayed but rather 404. But I'm on it!

fixed

**Comment by olayway** [comment]
![image](https://user-images.githubusercontent.com/52197250/198631204-f2e60020-71a7-4dc4-afd5-f9542a87671c.png)

**Comment by PhilippeduPreez** [comment]
https://imranhsayed.medium.com/adding-mailchimp-subscribe-newsletter-in-next-js-react-application-7c776daae710 possible solution for sending signups directly to mailchimp

**Comment by rufuspollock** [comment]
@olayway @PhilippeduPreez can we close this? I believe we said today this was already done 😄

**Comment by PhilippeduPreez** [comment]
FIXED
