### ISSUE TITLE
Error: ENOENT: no such file or directory, unlink '...flowershow/content'

### ISSUE THREAD

**Issue by aliamini87** [flowershow/flowershow#233]
I tried to install flowershow but ... the image below shows what happened. Then installing last forever!

windows10 with updated npm.

![image](https://user-images.githubusercontent.com/91720545/198506322-b1e76182-6b31-4d63-9e57-08bb2fe60698.png)

**Comment by olayway** [comment]
@aliamini87 Thank you so much for reporting the issue! Unfortunately, the Flowershow CLI is not yet supported on Windows. We have just added a warning that will be displayed in the command line when you try to run it on Windows, as well as a note in our tutorial.

Closing as the support for Windows is now being tracked in #234
