### ISSUE TITLE
CLI support for Windows

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#234]
## Known bugs

When running npx flowershow install on Windows:

![image](https://user-images.githubusercontent.com/52197250/198564342-8d09b82e-01fa-4cda-ac00-32f306a703d6.png)

Reported also here: https://github.com/flowershow/flowershow/issues/233#issue-1426675731

**Comment by Wittionary** [comment]
As a note to other people looking to try out Flowershow, it does work on WSL. It just requires a WSL-installation of nodejs.

**Comment by olayway** [comment]
Solved with #264

**Comment by olayway** [comment]
@Wittionary we've just fixed this issue on Windows so you should be able to use Flowershow without WSL. It's not yet thoroughly tested though, so let me know if you encounter any issues.
