### ISSUE TITLE
Upgrade to nextjs v13

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#253]
We want to upgrade to latest nextjs v13 as e.g. pliny uses it and we get latest stuff.

## Acceptance

- [ ] Flowershow upgraded to NextJS v13

## Tasks

- [ ] Analyze what is required
- [ ] Make upgrades

**Comment by olayway** [comment]
From Contentlayer repo:

![Image](https://user-images.githubusercontent.com/52197250/201326234-c18d94d4-5e9a-485d-b713-5afe83c191c5.png)

Right on time! 😄

**Comment by olayway** [comment]
One of the kbar dependencies requires React 16 or 17:

```bash
 WARN  Issues with peer dependencies found
packages/template
└─┬ kbar 0.1.0-beta.38
  ├─┬ @reach/portal 0.16.2
  │ ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
  │ ├── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
  │ └─┬ @reach/utils 0.16.0
  │   ├── ✕ unmet peer react@"^16.8.0 || 17.x": found 18.2.0
  │   └── ✕ unmet peer react-dom@"^16.8.0 || 17.x": found 18.2.0
  └─┬ react-virtual 2.10.4
    └── ✕ unmet peer react@"^16.6.3 || ^17.0.0": found 18.2.0
```

even though the latest kbar version lists React 18 as one of their peers:

https://github.com/timc1/kbar/blob/f557c85e48e2d20d8a87ae71c2830e88330ee0a4/package.json#L66-L69

Submitted an issue in the kbar repo: https://github.com/timc1/kbar/issues/256

**Comment by olayway** [comment]
Before this is fixed we could try suppressing the warning with:

```json
{
  "pnpm": {
    "peerDependencyRules": {
      "allowedVersions": {
        "react": "18"
      }
    }
  }
}
```

and see if kbar works as expected and then remove the above config after React 18 is supported by reach-ui

**Comment by olayway** [comment]
Kbar team has confirmed that it should work fine with React 18 (and that they should probably switch to using another portal lib as @reach/portal is not maintained).
https://github.com/timc1/kbar/issues/256#issuecomment-1315895099
