### ISSUE TITLE
Create a podcast landing page for next.lifeitself.org

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#266]
See https://github.com/life-itself/community/issues/193

**Comment by khalilcodes** [comment]
@rufuspollock wip for podcast layout and `content/podcast/index.md` page

**Comment by rufuspollock** [comment]
@khalilcodes great. can we track in https://github.com/life-itself/community/issues/193

**Comment by rufuspollock** [comment]
FIXED. this got done.
