### ISSUE TITLE
Support capitalized file and directory names

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#267]

**Comment by olayway** [comment]
@khalilcodes actually I think we shouldn't lower-case paths if they were created with capital letters. We should fix it in our wiki-links plugin.

https://www.searchenginejournal.com/google-urls-are-case-sensitive/421264/#:~:text=Two%20URLs%20could%20look%20the,%2C%20yes%20%E2%80%94%20these%20things%20matter.

**Comment by khalilcodes** [comment]
@olayway Fixed with latest package bump `v1.1.1`

**Note:** Obsidian doesn't allow to create both `/content/blog.md` and `/content/Blog.md` with error file already exists but allows `/content/blog.md` and `/content/blog/index.md`. That's a tricky situation. 😅
