### ISSUE TITLE
Table of content support in markdown

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#27]
When writing my page I want to include a table of contents in the main body of the page (at a location I choose) so that people can see the overview of what is written

Can be quickly implemented with https://github.com/remarkjs/remark-toc (though note connection with slug generation for headings)

## Acceptance

* [x] Can use some kind of indicator e.g. `## Table of Contents` or `{toc}` or whatever to embed a table of contents in current page at that location
* [x] No control at user level over ToC depth (should be max possible and set generally)

**Comment by olayway** [comment]
@rufuspollock, what do you mean by **in markdown**? I's this how it's supposed to work?

(from our docs)
![image](https://user-images.githubusercontent.com/52197250/179397026-6418c971-aa11-4090-b554-123e2629ddf2.png)

**Comment by olayway** [comment]
Maybe it would be better to use a boolean switch in frontmatter for this, instead of creating an empty heading?

**Comment by rufuspollock** [comment]
You often want to control where ToC shows up so boolean does not work as well. I think we can just use https://github.com/remarkjs/remark-toc
