### ISSUE TITLE
Add command "flowershow add [assets/components/getters]"

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#271]
The user might have not needed assets folder at the beginning. But then, if they need one, they would have to create a symlink to this folder manually. It would be good to also allow users to add custom components or getters folder using the CLI, so that they don't have to create and synlink them manually.

## Acceptance
- [ ] add command "flowershow add [assets/components/getters]"  or similar

**Comment by rufuspollock** [comment]
WONTFIX. Seems a nice to have and users sophisticated enough to use this stuff know how to symlink so wontfix for now.
