### ISSUE TITLE
Inline LaTeX shows on multiple lines

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#272]
![image](https://user-images.githubusercontent.com/52197250/201178157-96635e54-bf9e-4a89-8a62-c6359b5d34ea.png)

Renders as:
![image](https://user-images.githubusercontent.com/52197250/201178193-8ed4341c-d3dd-4d53-b437-7159c498ade7.png)

**Comment by rufuspollock** [comment]
This is definitely annoying. Moving to someday maybe for now as not urgent and want to see if someone comes in who wants to fix this.

**Comment by willjhliang** [comment]
Any news on this issue? It's the main thing stopping me from using Flowershow—would love to see it fixed up soon!

**Comment by olayway** [comment]
@willjhliang not yet. We'll look into this within the next 2 weeks.

**Comment by olayway** [comment]
@willjhliang this has just been fixed! Let us know if it works!
