### ISSUE TITLE
Data rich/literate documents analysis

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#286]
"Data ~~Literate~~ Rich Documents" is our terminology for markdown documents that includes tables, graphs etc as well as for straight up dataset publishing. The terminology emerged out of work over the years with DataHub and Datopian and see post about it in early 2021 on PortalJS https://portaljs.org/data-literate and the demo there.

## Acceptance

- [x] job stories written
- [ ] ideas for implementation

### General

I have markdown + data (csv, json, xlsx, sqlite?) and want to put it online with the *minimum* of fuss and complexity so that others can see and use my work

- I have a dataset i want to publish consisting of README plus a data file (or files) e.g. in CSV
- I have a data-driven story where i want to display data and/or charts in my markdown doc
- I have a data science analysis i quickly want to publish

On disk you have:

```bash
README.md
data.csv
```

In README i have something like:

```md
# My Amazing Dataset

This is my awesome dataset / data driven analysis.

Here's the data

<DataTable src="mydata.csv" />

You can create a nice chart like this:

<LineChart config={} data="mydata.csv" />
```

And pfft in a puff of smoke this turns into a nice rendered page with a table and Line Chart. Here was the demo:

https://portaljs.org/data-literate/demo

### Data Table

When creating a markdown page I want to display a data table in it so that people can understand what i am talking about

- inline data e.g. json, or even inline csv
- data from a separate file
- primary data types: csv, json. But also xlsx and then many others

### Graph

When creating a markdown page I want to display a graph of data so that people can understand what i am talking about

**Comment by rufuspollock** [comment]
FIXED. See details in issue description.
