### ISSUE TITLE
Adjust E2E CLI tests to use current version of the template rather than degitted one (?)

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#287]
so that e2e tests run locally take into account changes made to the template before the they are merged to main and can be degitted by CLI

Remember to:
- add the template back as an implicit dependency of CLI for nx

**Comment by rufuspollock** [comment]
My thoughts here: CLI tests should be testing the CLI. If the template breaks the CLI on some way that would show up in merge in main (and should be rare). I think we should keep CLI tests using the actual CLI workflow. I get the subtlety here though. I suggest we don't do this immediately though and think a bit.

**Comment by rufuspollock** [comment]
WONTFIX.
