### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'length') 

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#289]
When running `npm run dev` or `npx nx serve template` sometimes this error shows up:

```
TypeError: Cannot read properties of null (reading 'length')
    at eval (webpack-internal:///./node_modules/next/dist/client/dev/error-overlay/hot-dev-client.js:262:55)
```

The server starts despite the error and it builds successfully.

**Comment by rufuspollock** [comment]
WONTFIX. Nothing really here atm. Let's close and re-open if it comes up again and creates a problem.

Suspicion it relates to search components.
