### ISSUE TITLE
Integrate our remark plugins in the flowershow monorepo

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#303]
## Acceptance

Integrated:
- [x] remark-wiki-link-plus
- [x] remark-callouts
- [x] remark-embed-plus
- [ ] wordpres-export-to-markdown-plus (?)

Other:
- [ ] run tests for the integrated packages in CI workflow

**Comment by olayway** [comment]
@rufuspollock what about our wordpress-to-markdown script?

**Comment by rufuspollock** [comment]
@olayway i think that stays independent for now.
