### ISSUE TITLE
'process is not defined' error when importing components that include Next.js Link in MDX files

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#319]
## Bug description
Importing React components that include Next.js's `Link` into MDX files results in the following client-side error:

![image](https://user-images.githubusercontent.com/52197250/184024132-8b96b89a-85c2-43f3-95fd-0a7980252192.png)

## Notes
This issue has been reported in Contentlayer's repo: https://github.com/contentlayerdev/contentlayer/issues/288

**Comment by rufuspollock** [comment]
@olayway posted a minimal repro days ago and the owner has not yet got back to it.
