### ISSUE TITLE
Update self-publish Tutorial

### ISSUE THREAD

**Issue by PhilippeduPreez** [flowershow/flowershow#344]
## Acceptance
- [x] all steps in our self-publish tutorial are up to date and easy to understand to a first time user

## Tasks
- [x] review our self-publish tutorial and make necessary fixes while following along the steps in it **2023/01/30 See [commit](https://github.com/flowershow/flowershow/commit/c3dd1d66881e0d39206be667c4672717d8372f17)**

**Comment by rufuspollock** [comment]
@PhilippeduPreez i'm moving this out of the sprint if that is ok - is there any reason to think it is out of date?

**Comment by PhilippeduPreez** [comment]
@rufuspollock I think mostly just replacing `flowershow` commands with `flowershow@latest` **If omitting @latest causes problems sometimes**

**Comment by PhilippeduPreez** [comment]
FIXED, see commit [here](https://github.com/flowershow/flowershow/commit/c3dd1d66881e0d39206be667c4672717d8372f17)
