### ISSUE TITLE
Wordpress to (flowershow) markdown tutorial v0.2

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#356]
## Acceptance

- [x] Updated blog tutorial with nicer images **Done 2022/12/19**

### Improvements to tutorial

- [x] Summarize steps at the start (excluding preliminaries) in a short list so people know what is involved
- [x] Screenshots of before and after
- [x] Separate section on adding content (see below) #363 
- [x] Clearer and extended section of FAQs section at end
  - [x] See questions below
  - [x] Also things like:
    - [x] what happens to my blog index page. Ans: see our tutorial on setting up your blog here.

Steps improvements

- [x] (Preliminaries) Install node (if you haven't) 🆕
- [x] Export from wordpress
  - [x] comment about on wordpress.com looking different
- [x] Get the script (and setup)
  - [x] (is there a way to do this without git e.g. get the tarball) **sticking with git, think it is simpler for user**
- [x] Run the script
  - [x] Give a simple example of command line
  - [x] Or wizard
  - [x] Flag that for more information see the README
    - [x] Note: you have replace README with tutorial. Personally, i'd keep the README as was (more of reference with command line arguments) and just link to our blog tutorial at top of README
      - [x] Why? because tutorial will get updated etc.
- [x] Integrate content into your flowershow site 🆕

Minor

- [x] Table of contents (why is this not showing up on RHS?) For now could add explicitly using `[toc]` (IIRC) #284

### Questions

- What happens to categories? **✅2022-12-07 they get outputted to the `categories` front matter**
  - What happens to category info itself e.g. its full name (vs its slug)
- What happens to tags? **✅2022-12-07 they get outputted to `tags` field**
- What happens to featured image? **✅2022-12-07 this is set in `image` property of frontmatter**
- What happens to other metadata? e.g. do we have an option to keep *all* wordpress metadata in frontmatter (perhaps prefixed with `wp_` or similar?)

**Comment by PhilippeduPreez** [comment]
@rufuspollock Please let know if  updated Tutorial needs anymore adjustments https://hackmd.io/Uq2yzonrQn6z2x8WfqjcIA?both

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you submit this as a draft PR and i review that way, please.

BTW going forward i think a draft PR is better even for new content than a hackmd.

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you confirm that all items were completed - and did @olayway get to review?
