### ISSUE TITLE
Authors / Users support in wordpress export

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#358]
When exporting my wordpress site I want the users exported and linked to blog post (and pages) so that they are displayed with full info on my new markdown-based site

## Acceptance

- [ ] All wordpress users to the Flowershow style author/person markdown objects - https://flowershow.app/docs/blog#blog-authors
  - [ ] author avatar picture downloaded (or link set if external link)  
- [ ] `authors` attribute set on posts on pages with correct id

**Comment by rufuspollock** [comment]
@khalilcodes do we already support this?

**Comment by khalilcodes** [comment]
@rufuspollock no the tool does not export wordpress users (or user's data). We will have to add this to create an author's folder with *wordpress user's* data as frontmatter.

*Note in Life Itself:*
Although, for LI we have a *teams* tab and it generates the md for those (name & avatar/image), but the authors frontmatter in all pages/blogs are not associated with those. The authors are actually *wordpress users*.

**Comment by khalilcodes** [comment]
@rufuspollock starting to work on this ...

**Comment by rufuspollock** [comment]
@khalilcodes ok, can you spec out a little how you expect this to work. e.g. what attributes you'll migrate, whether you'll migrate all users (i assume not) or just those with articles etc.

**Comment by rufuspollock** [comment]
@khalilcodes is this done?

**Comment by khalilcodes** [comment]
@rufuspollock Yes, I'll update the acceptance and close.

**Comment by khalilcodes** [comment]
Updated Acceptance / tasks and closing as completed.
