### ISSUE TITLE
Failed installing Flowershow due to no matching dependency found

### ISSUE THREAD

**Issue by mburazin** [flowershow/flowershow#395]
Hi,

Trying to install Flowershow as described in the documentation using:

`npx flowershow@latest install`

But the script fails when installing dependencies:

```
ERROR  Failed to install Flowershow dependencies: Command failed with exit code 1: npm install
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @flowershow/core@^0.0.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/markoburazin/.npm/_logs/2023-01-23T19_43_09_670Z-debug-0.log
FAIL: 1
```

**Comment by olayway** [comment]
@mburazin My bad, I forgot to publish `@flowershow/core` 0.0.10 🤦‍♀️. Done now. Can you try again?

**Comment by mburazin** [comment]
> @mburazin My bad, I forgot to publish `@flowershow/core` 0.0.10 🤦‍♀️. Done now. Can you try again?

Thanks @olayway ! Working now 👍

**Comment by olayway** [comment]
Closing as it works now
