### ISSUE TITLE
No "out" folder with static files after building with export 

### ISSUE THREAD

**Issue by mburazin** [flowershow/flowershow#398]
Hi,

I'm trying to deploy to Netlify but failing.

According to the docs found [here](https://flowershow.app/docs/publish-tutorial#build-your-website), to build static files I need to run the command: `npx flowershow export`, but that in fact generates `.flowershow/.next` directory. I cannot find the `out` folder mentioned in the docs.

Is there anything else I'm missing ? Is the documentation correct?

Thanks!

**Comment by PhilippeduPreez** [comment]
Hi @mburazin ! Can you check whether it works when you run `npx flowershow@latest export`

**Comment by mburazin** [comment]
@PhilippeduPreez Tried and no, it didn't work. Still no `out` folder generated

**Comment by rufuspollock** [comment]
@PhilippeduPreez can you reproduce or not?

**Comment by PhilippeduPreez** [comment]
@mburazin I am not getting this error, could you paste the feedback you are getting from the terminal after running `npx flowershow@latest export` . Also which OS are you using?

**Comment by mburazin** [comment]
Here's the OS info and the command output:

```
markoburazin@Markos-MacBook-Pro: ~/workspace/Notes/Marko's Second Brain main ⚡
$ uname -a                                                                                                                                                          [14:12:30]
Darwin Markos-MacBook-Pro.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:04:44 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T8103 arm64
 
markoburazin@Markos-MacBook-Pro: ~/workspace/Notes/Marko's Second Brain main ⚡
$ npx flowershow@latest export                                                                                                                                      [14:12:35]

> @flowershow/template@1.0.0 export
> npm run build && next export


> @flowershow/template@1.0.0 build
> next build

Generated 1 documents in .contentlayer
info  - Skipping linting
info  - Checking validity of types...
 
markoburazin@Markos-MacBook-Pro: ~/workspace/Notes/Marko's Second Brain main ⚡
$ ls -al .flowershow                                                                                                                                                [14:12:52]
total 1232
drwxrwxr-x   25 markoburazin  staff     800 Jan 24 23:30 .
drwxrwxr-x@  11 markoburazin  staff     352 Jan 24 17:58 ..
drwxr-xr-x    5 markoburazin  staff     160 Jan 25 14:12 .contentlayer
drwxr-xr-x    3 markoburazin  staff      96 Jan 24 23:30 .next
-rw-r--r--    1 markoburazin  staff     213 Jan 24 11:50 README.md
drwxrwxr-x    3 markoburazin  staff      96 Jan 24 17:58 components
drwxrwxr-x    3 markoburazin  staff      96 Jan 24 17:58 config
lrwxr-xr-x    1 markoburazin  staff      17 Jan 24 17:58 content -> ../Digital Garden
-rw-r--r--    1 markoburazin  staff    6947 Jan 24 11:50 contentlayer.config.ts
drwxrwxr-x    3 markoburazin  staff      96 Jan 24 17:58 layouts
drwxrwxr-x    4 markoburazin  staff     128 Jan 24 17:58 lib
-rw-r--r--    1 markoburazin  staff     201 Jan 24 11:50 next-env.d.ts
-rw-r--r--    1 markoburazin  staff     255 Jan 24 11:50 next.config.mjs
drwxr-xr-x  476 markoburazin  staff   15232 Jan 24 18:01 node_modules
-rw-r--r--    1 markoburazin  staff  582861 Jan 24 18:01 package-lock.json
-rw-r--r--    1 markoburazin  staff    1470 Jan 24 18:01 package.json
drwxrwxr-x    5 markoburazin  staff     160 Jan 24 17:58 pages
-rw-r--r--    1 markoburazin  staff     204 Jan 24 11:50 postcss.config.js
drwxrwxr-x    4 markoburazin  staff     128 Jan 24 17:58 public
drwxrwxr-x    3 markoburazin  staff      96 Jan 24 17:58 scripts
drwxrwxr-x    5 markoburazin  staff     160 Jan 24 17:58 styles
-rw-r--r--    1 markoburazin  staff    1288 Jan 24 11:50 tailwind.config.cjs
-rw-r--r--    1 markoburazin  staff     984 Jan 24 11:50 tsconfig.json
-rw-r--r--    1 markoburazin  staff      82 Jan 24 11:50 tsconfig.mdx.json
-rw-r--r--    1 markoburazin  staff      47 Jan 24 11:50 types.d.ts
 
markoburazin@Markos-MacBook-Pro: ~/workspace/Notes/Marko's Second Brain main ⚡
$
```

**Comment by PhilippeduPreez** [comment]
@olayway I tried again with a new install and now I also don't seem to be producing the `out` folder. Could this be due to typescript changes or any updates lately?

**Comment by romovpa** [comment]
I have the same problem as @mburazin described. OSX. 

With the newly initialized website and empty `config.js` (`{}`), export does not generate `out`:
```
 ~/workspace/website/ [main] npx --version
9.3.1
 ~/workspace/website/ [main] npx flowershow@latest export

> @flowershow/template@1.0.0 export
> npm run build && next export


> @flowershow/template@1.0.0 prebuild
> npm run generate


> @flowershow/template@1.0.0 generate
> contentlayer build && cross-env NODE_OPTIONS="--experimental-json-modules --experimental-modules" node ./scripts/search.mjs

Generated 2 documents in .contentlayer

> @flowershow/template@1.0.0 build
> next build

Generated 2 documents in .contentlayer
info  - Skipping linting
info  - Checking validity of types...
 ~/workspace/website/ [main] ls .flowershow/.next 
BUILD_ID                     export-detail.json           next-server.js.nft.json      react-loadable-manifest.json server
build-manifest.json          export-marker.json           package.json                 required-server-files.json   static
cache                        images-manifest.json         prerender-manifest.json      routes-manifest.json         trace
 ~/workspace/website/ [main] ls .flowershow/out     
ls: .flowershow/out: No such file or directory
```

The problem has gone when I changed the `config.js` with an example from [this page](https://flowershow.app/docs/config).

**Comment by rufuspollock** [comment]
@olayway a) i believe we need a `config.js` (and this should be created during install) b) maybe we need to warn in export if no config.js (though not sure - people should have installed ok ... so this seems fixing something later in the process)

@PhilippeduPreez what exactly were your steps to reproduce? How were you installing flowershow (what command did you run etc).

**Comment by PhilippeduPreez** [comment]
@rufuspollock @olayway 
Similar to @romovpa I am finding the following:

Starting new site with `npx flowershow@latest install`

Then running `npx flowershow@latest export`

Only leads to:
```
~/Projects/testing$ npx flowershow@latest export

> @flowershow/template@1.0.0 export
> npm run build && next export


> @flowershow/template@1.0.0 build
> next build

Generated 2 documents in .contentlayer
info  - Skipping linting
info  - Checking validity of types...
```

Where no `output` folder is created and the `.next` folder only contains a `.cache` folder with `.tsbuildinfo`

**However**, if the empty config `{}` is changed to the following:

```
const config = {
  };
  export default config;
```

Then everything works as expected.

**Comment by PhilippeduPreez** [comment]
@mburazin Please let know if just adding the following in your `content/config.js` solves your problem:

Instead of `{}`
Replace with

```
const config = {};
export default config;
```

**Comment by PhilippeduPreez** [comment]
@olayway Can we change the default `config.js` being created to contain 
```
const config = {};
export default config;
```
Instead of `{}`

As this seems to fix the `npx flowershow@latest export` error of not producing an `out` folder

Except if you have a better fix?

**Comment by olayway** [comment]
@PhilippeduPreez

> Can we change the default config.js being created to contain ...
I'm on it!

**Comment by olayway** [comment]
@PhilippeduPreez done. Can you please test if it works now?

**Comment by PhilippeduPreez** [comment]
@olayway It works! FIXED [here](https://github.com/flowershow/flowershow/commit/dce281412184a972b2e4bdc95f5644f481b0ae20)

**Comment by romovpa** [comment]
> Can we change the default config.js being created to contain

Why not include commented example fields for quicker onboarding in the default configuration?

**Comment by mburazin** [comment]
@PhilippeduPreez Yup, just confirmed that it's working for me as well if I change the `config.js` file as specified.

Thanks everyone!

**Comment by olayway** [comment]
> Why not include commented example fields for quicker onboarding in the default configuration?

@romovpa thank you for your suggestion! We'll be working on tidying up our docs, i.a. the page on Flowershow configuration with `config.js` file. After this is done I'll add the correct default configuration to our installation script. Here is the issue I've just created out of your comment, thank you! 🌻 #411
