### ISSUE TITLE
Site-wide Table of Contents v.2.

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#408]
## Acceptance

- [ ] displays all pages grouped by content subfolders

## Notes

- only one level grouping?
  - i.e. group by content/<folder> and include files in subfolders of <folder> in this group as well

**Comment by PhilippeduPreez** [comment]
@olayway Requests from discord users: We can maybe have a preview of how it looks in the docs. (I know design isn't finished yet :) )

**Comment by olayway** [comment]
@PhilippeduPreez done! https://flowershow.app/docs/site-wide-toc

**Comment by StefanoCecere** [comment]
it's strange that here https://flowershow.app/docs/site-wide-toc we see a screenshot of the callout page with the list of all the contents in the sidebar, but if we go to that page https://flowershow.app/docs/callouts the sidebar is empty!
