### ISSUE TITLE
Mermaid graphs not rendering on deployed site?

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#422]
See e.g. https://lifeitself.org/notes/projects/digital-garden-2022. Oddly works locally.

![image](https://user-images.githubusercontent.com/180658/217540768-b3f72ee1-fa51-41e4-a92c-dd1a9b8d5b32.png)

**Comment by olayway** [comment]
@rufuspollock I'm adding this to our next sprint as well.

**Comment by rufuspollock** [comment]
@khalilcodes good find of mermaid issue. for now just having it render (even if overlap problem) is great progress and would be great if we can ship this fix and then pull downstream.

**Comment by olayway** [comment]
@khalilcodes Great job! Thank you for taking care of it so quickly!

As for the overlapping nodes, I've found a similar issue on the mermaid repository. Sb has the same problem on Next.js, i.e. works on dev but not after build and start.

https://github.com/mermaid-js/mermaid/issues/3854

**Comment by olayway** [comment]
Closing as this works in the current `@flowershow/core` package version (`0.2.1`).
