### ISSUE TITLE
Text highlighting support

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#43]
Text wrapped in double `=` should be highlighted.

**Obsidian:**
![Screenshot_2022-07-16_20-58-52](https://user-images.githubusercontent.com/52197250/179368579-bb9ae917-ed9c-4189-8d91-afebcdb0eab1.png)

**Flowershow:**
![image](https://user-images.githubusercontent.com/52197250/179368599-64374c86-8dad-4b4c-8db7-3859abcef50e.png)

**Comment by rufuspollock** [comment]
WONTFIX. I'm going to close as wontfix for now as I don't think we want/need to support this IMO. I've never used it and never seen anyone use it and it's nonstandard commonmark.
