### ISSUE TITLE
Broken links to index pages (when using obsidian)

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#46]
## What happens?
Internal links created in Obsidian, that point to `some_folder/page_name` are converted - as expected - to URLs which end with `some_folder/page_name`. Unfortunately, `index.md` pages are treated exactly the same, so resulting URLs end with `some_folder/index`, which results in 404.

**Example:**
In `docs/index` page, I'm creating an internal link to `demo/index` page, like so: `[[demo/index]]`. A resulting anchor tag will point to `[...]/demo/index`, instead of `[...]/demo`.

## Temporary workaround
Manually remove `/index` part from `[[demo/index]]` link automatically created by Obsidian, and leave `[[demo]]` only.

**Comment by rufuspollock** [comment]
My guess is easiest proper fix for this would be in wiki links remark plugin

**Comment by khalilcodes** [comment]
@olayway this bug has been fixed with the latest update in remark-wiki-link-plus ie., v1.0.1 and package.json has been updated to reflect the changes.

**Comment by rufuspollock** [comment]
@khalilcodes i'd have also liked that README.md also worked the same way - is that an easy fix?

**Comment by khalilcodes** [comment]
@rufuspollock yes I believe it is and will update soon. 👍

**Comment by olayway** [comment]
@khalilcodes Works! Thank you 🌷!
