### ISSUE TITLE
Research how we can build a richer metadata database to build site from

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#5]
Research how we can build a richer metadata database to build site from e.g. that includes forward/back links so that we can display that information

**UPDATE 2023-03-24: we have done extensive research and arrived at a solution which is to build our own sqlite-based metadata database termed [markdowndb]. This effort is already well advanced and we are actively using a prototype markdowndb in live projects**

[markdowndb]: https://datahub.io/notes/markdowndb

## Tasks

* [x] Research how obsidian does this **🚧2022-11-06 see ~~https://flowershow.app/notes/obsidian-database-research~~ https://datahub.io/notes/obsidian**
* [x] Research if contentlayer allows richer pre/post processing of markdown **✅2023-03-24 no it doesn't**

## Notes

Backlinks are complex as they will require processing *all* documents.

**Comment by rufuspollock** [comment]
Yes

**Comment by olayway** [comment]
Not sure yet, but I think code of this obsidian plugin can be worth checking out:
https://github.com/blacksmithgu/obsidian-dataview

**Comment by rufuspollock** [comment]
> Not sure yet, but I think the code of this obsidian plugin may be worth checking out:
[blacksmithgu/obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview)

👍 and had already been looking at that. notes coming soon.

**Comment by rufuspollock** [comment]
Posted research so far in https://flowershow.app/notes/obsidian-database-research

**Comment by thoughtship** [comment]
Hey @rufuspollock, 
The link you posted is broken. [Here's the working link.](https://github.com/flowershow/flowershow/blob/main/site/content/notes/obsidian-database-research.md) for anyone interested.

Saw you're looking at the dataview extension.  Zsolt Viczian has extended it to determine the relationships of a node. He had been working with Obsidian for a long time already when he released this. Perhaps you can re-use some of his code for your purposes? 
https://github.com/zsviczian/excalibrain/blob/master/src/graph/

If you don't want parent-child relationship It seems this logic can also could be changed just to show an existing relationship between nodes. 
https://github.com/zsviczian/excalibrain/blob/master/src/graph/Links.ts

**Comment by rufuspollock** [comment]
@thoughtship thanks for the suggestions, really useful and i will take a look.

I'm actually quite hopeful we will have this resolved quite soon as we are working on a "markdowndb". You can track the progress in this issue here https://github.com/datopian/datahub-next/issues/46

(For context: DataHub Next uses Flowershow and is pioneering some of the features that will show up Flowershow "v2")

**Comment by rufuspollock** [comment]
Updating here: we are making excellent progress on a "markdowndb" https://datahub.io/notes/markdowndb which gives us a much richer metadata etc. ETA on this landing in Flowershow is mid April.

**Comment by rufuspollock** [comment]
FIXED. We have done research and are building [markdowndb](https://datahub.io/notes/markdowndb).
