### ISSUE TITLE
Draft an email with latest and upcoming changes for subscribers

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#85]
## Acceptance
- [x] draft of an email with the latest and upcoming changes **06-10-22 https://hackmd.io/fbM5Mg0IRaKzzDCl5kULNw?both**
- [x] email sent to subscribers

## Notes
V.1
![image](https://user-images.githubusercontent.com/52197250/195302822-1981b613-0c5f-408b-8613-bfd2e1f16692.png)
![image](https://user-images.githubusercontent.com/52197250/195303077-7d6359ce-8125-481e-96cc-f8399b87fb64.png)

**Comment by olayway** [comment]
@rufuspollock The email draft is ready. I have used stripo template builder to make it look nice and sent it to you in a test email on Oct 7th ([test]🌷 Flowershow has new features!). Let me know if it looks good to you.

**Comment by olayway** [comment]
Oh, I will also add a link to our brand new Discord server and maybe even list it in "What's new"!

**Comment by rufuspollock** [comment]
Looks good, let's send today (maybe check if we can track (anonymous) opens somehow). Can just bcc the user list and send from your lifeitself account!

**Comment by olayway** [comment]
For future reference: https://support.google.com/mail/answer/81126?hl=en

**Comment by olayway** [comment]
Email sent on 12.10.2022
