### ISSUE TITLE
Separate default (template) components and user defined components

### ISSUE THREAD

**Issue by olayway** [flowershow/flowershow#88]
When customizing/enhancing my site I want to know how to use components (and data for them) so that I can cleanly separate from custom content from flowershow (so that i can do upgrades, keep things simple)

## Acceptance

* [x] This works ✅ **2022-08-17 works, we have our custom components for Flowrshow website in `site/components` folder**
* [x] Documented in the docs ✅ **2022-08-17 done, 2022-08-24 improved**

## Notes

**olayway**: As of 2022-08-17 separation of the template and user-defined components is accomplished in the following way:

Users can add their custom components in a separate folder, outside of Flowershow's template folder, e.g. in a parent folder of their content folder, e.g.:

```bash
site
├── components
└── content
```
This would already work (at least when testing locally; not sure why it doesn't throw an error...), however, import paths would look like this:

```md
import MyComponent from "../../site/components/MyComponent.jsx"
```
...which is a bit confusing. I'm not even sure relative to what folder this path is  but normally we use `../components/SomeTemplateComponents.jsx` to import template-defined components, so I've figured out the path for custom components based on that.

In order to make the paths a bit simpler (?) a user can create a symlink to their components folder in the Flowershow's template components folder (under e.g. `custom` name):

```bash
cd templates/default/components
ln <path-to-custom-components-folder> custom
```
Now components can be imported using this path:

```md
import MyComponent from "../components/custom/MyComponent.jsx"
```
Which is  a bit better I think, but in the absence of a CLI tool requires manual symlink creation.

**Comment by olayway** [comment]
@rufuspollock, @khalilcodes see my comments above re how we're currently separating template components from custom components. Let me know if you have some thoughts on that.

**Comment by olayway** [comment]
Btw, I've tried to figure out the starting point (folder) for components import paths in MDX files (e.g. ../components/SomeTemplateComponents.jsx) but without success. Do you maybe know what it is?

**Comment by rufuspollock** [comment]
@olayway should this move into the the site content somewhere e.g. docs (?)

**Comment by olayway** [comment]
@rufuspollock I had already described it shortly in our docs before but I've tweaked the description a bit:

![image](https://user-images.githubusercontent.com/52197250/186398223-49864a79-7761-4691-9a14-827c9f711041.png)

Is it ok?

**Comment by rufuspollock** [comment]
@olayway ok, i'm just checking because what you've written above seemed really clear: 

> Users can add their custom components in a separate folder, outside of Flowershow's template folder, e.g. in a parent folder of their content folder, e.g.:
> 
> ```
> site
> ├── components
> └── content
> ```
> 
> Import paths would look like this:
> 
> import MyComponent from "../components/custom/MyComponent.jsx"

I think at this point we want the docs to follow our recommended path.

**Comment by olayway** [comment]
@rufuspollock added this as a last section to mdx docs page


![Image](https://user-images.githubusercontent.com/52197250/186718087-69ce0494-7bb7-4c6d-8680-2bb90f3a93ff.png)

**Comment by rufuspollock** [comment]
@olayway sounds good for now. I think we can now close this. I'll leave you the honors.
