### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by rufuspollock** [flowershow/flowershow#99]
We want an about page telling more about the project

## Acceptance

* [x] Why: motivation/our passion + overall need **✅2022-08-23 brief intro - a tool for publishing your digital garden**
* [x] What: what are we aiming to build (vision) **✅2022-08-23 bigger vision**
* [x] Who: Team **✅2022-08-25 have Rufus and Ola which is enough for now** **🚧2022-08-23 added rufus. Now needs e.g. @olayway bio and headshot**
* [x] story: behind the project - how did we come to this **✅2022-08-23 backstory**
* [x] Stay in touch / get connected **❌2022-08-23 not sure we need this for now - we have the forum**

**Comment by olayway** [comment]
@rufuspollock I think you have more to say in this matter 😀 I'm not even sure where to start. I think it would be better if you prepared a draft or even bullet points and I would start from there.

**Comment by rufuspollock** [comment]
@olayway now have a page up https://flowershow.app/about - would you be up for adding yourself as a team member - can link your avatar for headshot and have a brief bio.

**Comment by rufuspollock** [comment]
FIXED.  See https://flowershow.app/about
